'use client'
import {ConditionProfile,Dev} from '@/types/lab.types'
const BADGE:Record<Dev,string>={normal:'bg-green-50 text-green-700',mild:'bg-amber-50 text-amber-700',moderate:'bg-orange-50 text-orange-700',significant:'bg-red-50 text-red-700'}
const FILL:Record<Dev,string>={normal:'#22c55e',mild:'#f59e0b',moderate:'#f97316',significant:'#ef4444'},PCT:Record<Dev,number>={normal:96,mild:80,moderate:60,significant:35}
const card='bg-white dark:bg-[#161616] rounded-2xl p-5 border border-gray-100 dark:border-[#1f1f1f] shadow-sm dark:shadow-none'
export default function AIAssessmentPanel({c,done}:{c:ConditionProfile;done:boolean}){
 return <>
  <div className={card}><div className="flex justify-between items-center"><div className="text-[12pt] font-bold text-gray-900 dark:text-[#f0f0f0]">AI MOVEMENT ASSESSMENT</div><span className="text-[8pt] bg-amber-100 text-amber-700 rounded-full px-2 py-0.5 font-medium">DEMO</span></div>
   {!done?<div className="py-8 text-center"><svg width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="#d1d5db" strokeWidth="1.2" className="mx-auto"><path d="M9 4a3 3 0 0 0-3 3 3 3 0 0 0-2 5 3 3 0 0 0 2 5 3 3 0 0 0 6 1V4a3 3 0 0 0-3 0zM15 4a3 3 0 0 1 3 3 3 3 0 0 1 2 5 3 3 0 0 1-2 5 3 3 0 0 1-6 1"/></svg><div className="text-[12pt] text-gray-400 dark:text-[#555] mt-2">Run a simulation to see the AI assessment</div></div>
   :<><div className="mt-4 rounded-xl p-4 border-l-4" style={{borderColor:c.color,background:c.color+'0d'}}><div className="flex justify-between"><span className="text-[9pt] uppercase tracking-wide" style={{color:c.color}}>Pattern detected</span><span className="text-[8pt] bg-white dark:bg-[#0d0d0d] border border-gray-200 dark:border-[#2a2a2a] rounded-full px-2 py-0.5 text-gray-600 dark:text-[#888]">{c.evidenceLevel}</span></div><div className="text-[15pt] font-bold text-gray-900 mt-1">{c.label}</div></div>
    <p className="mt-4 text-[13pt] text-gray-700 dark:text-[#ccc] leading-relaxed">{c.patternSummary}</p>
    <div className="mt-4 bg-amber-50 dark:bg-amber-500/10 border border-amber-100 dark:border-amber-500/30 rounded-xl p-4"><div className="text-[9pt] uppercase tracking-wide text-amber-700">Recommended action</div><div className="text-[12pt] text-amber-900 dark:text-amber-300 mt-1">{c.recommendedAction}</div></div></>}</div>
  <div className={card}><div className="text-[12pt] font-bold text-gray-900 dark:text-[#f0f0f0]">BIOMARKER ANALYSIS</div><div className="text-[10pt] text-gray-500 dark:text-[#666]">Quantitative movement features · bars show deviation severity, not measured values</div>
   {c.biomarkers.map((b,i)=><div key={b.name} className={`mt-4 ${i?'border-t border-gray-50 dark:border-[#1a1a1a] pt-4':''}`}><div className="flex justify-between items-start"><span className="text-[12pt] font-medium text-gray-900">{b.name}</span><span className={`text-[9pt] rounded-full px-2 py-0.5 ${BADGE[b.deviation]}`}>{b.deviation}</span></div>
    <div className="flex gap-6 mt-2"><div><div className="text-[9pt] text-gray-400 dark:text-[#555]">Patient</div><div className="text-[13pt] font-mono" style={{color:b.deviation==='normal'?c.color:FILL[b.deviation]}}>{b.value}</div></div><div><div className="text-[9pt] text-gray-400 dark:text-[#555]">Reference</div><div className="text-[13pt] font-mono text-gray-500 dark:text-[#888]">{b.reference}</div></div></div>
    <div className="relative h-1.5 bg-gray-100 dark:bg-[#1a1a1a] rounded-full mt-2"><div className="absolute inset-y-0 left-0 w-full rounded-full bg-blue-200"/><div className="absolute inset-y-0 left-0 rounded-full opacity-80" style={{width:`${PCT[b.deviation]}%`,background:FILL[b.deviation]}}/></div>
    <div className="text-[10pt] text-gray-400 dark:text-[#555] italic mt-1.5">{b.description}</div></div>)}</div>
  <div className="bg-amber-50 dark:bg-amber-500/10 border border-amber-200 dark:border-amber-500/30 rounded-2xl p-5"><div className="text-[12pt] font-bold text-amber-800 dark:text-amber-300">⚠ Important Notice</div><p className="text-[11pt] text-amber-700 dark:text-amber-400/90 leading-relaxed mt-2">{c.disclaimer}</p>
   <p className="text-[11pt] text-amber-700 dark:text-amber-400/90 leading-relaxed mt-2">This simulation is intended for research, education and demonstration only. It does not constitute medical advice. Clinical diagnosis requires specialist evaluation and validated clinical tools.</p></div></>}
