import {ConditionKey,ConditionProfile,SimFrame,Dev} from '@/types/lab.types'
// SIMULATED reference profiles for demonstration — not clinical thresholds.
type Bm=[string,string,string,Dev,string]
// n = [rom,speed,variability,tremorAmp,tremorHz,initDelayMs,smoothness,asymmetry,grip,emg,emgVar,wristComp,wristTremor]
const P=(key:ConditionKey,label:string,category:any,color:string,severity:any,n:number[],fm:number[],description:string,patternSummary:string,recommendedAction:string,evidenceLevel:any,disclaimer:string,bm:Bm[]):ConditionProfile=>({key,label,category,color,severity,description,
 romScale:n[0],speedScale:n[1],variabilityScale:n[2],tremorAmplitude:n[3],tremorFrequency:n[4],initiationDelay:n[5],smoothnessScale:n[6],asymmetryScale:n[7],gripStrengthScale:n[8],emgScale:n[9],emgVariabilityScale:n[10],wristCompensation:n[11],wristTremorScale:n[12],
 fingerModifiers:fm,patternSummary,recommendedAction,evidenceLevel,disclaimer,biomarkers:bm.map(([name,value,reference,deviation,description])=>({name,value,reference,deviation,description}))})
export const CONDITIONS:Record<ConditionKey,ConditionProfile>={
 healthy:P('healthy','Healthy Reference','Reference','#0F6E5E','Ref',[1,1,1,.8,10,80,1,0,1,1,1,.05,.1],[1,1,1,1],'Normal age-matched movement reference profile',
  'Movement profile within normal reference range. ROM, speed, and coordination consistent with healthy baseline. No anomalous patterns detected.','No clinical follow-up indicated. Continue monitoring.','Reference','This is a simulated reference profile for demonstration purposes.',
  [['ROM','82°','82°','normal','Full flexion range at or above reference'],['Movement Speed','1.1s','1.1s','normal','Movement time within normal range'],['Smoothness','High','High','normal','Trajectory is smooth and controlled'],['Tremor','<1°','<2°','normal','Physiological tremor only'],['EMG Activation','Normal','Normal','normal','Activation consistent with healthy profile']]),
 parkinsonian:P('parkinsonian','Parkinsonian Pattern','Neurological','#8b5cf6','High',[.62,.55,1.8,7.5,4.8,420,.55,.35,.65,.72,1.9,.25,.8],[.65,.62,.68,.7],"Simulated profile with features associated with Parkinson's disease motor characteristics",
  'Features associated with the Parkinsonian reference cohort: reduced amplitude (↓38%), prolonged movement time (↑82%), elevated rep-to-rep variability, and an oscillatory signal consistent with resting tremor (~4–5Hz). Initiation latency ~420ms. Clinical evaluation is recommended.','Refer for neurological assessment. Quantitative motor features warrant clinical evaluation.','Emerging evidence',
  'Simulated reference profile for research and demonstration only. Not a diagnostic tool. Clinical diagnosis requires specialist evaluation.',
  [['ROM','51°','82°','significant','Reduced amplitude (bradykinesia) is a key motor feature'],['Movement Speed','2.0s','1.1s','significant','Prolonged movement time. Reference <1.4s'],['Tremor Frequency','4.8Hz','<2Hz','significant','Resting tremor 4–6Hz is characteristic'],['Tremor Amplitude','7.5°','<1°','significant','Well above physiological range'],['Initiation Delay','420ms','<100ms','significant','Delayed movement initiation'],['Inter-rep Variability','+82%','<20%','significant','Motor inconsistency between repetitions'],['Smoothness','Reduced','High','moderate','Fragmented trajectory'],['EMG Pattern','Irregular','Regular','moderate','Altered burst pattern, reduced coordination']]),
 stroke_mild:P('stroke_mild','Post-Stroke (Mild)','Neurological','#f97316','Mod',[.72,.68,1.5,2,6,220,.7,.65,.6,.78,1.4,.45,.3],[.75,.7,.68,.6],'Simulated mild upper limb motor impairment following stroke',
  'Features consistent with mild upper-limb motor impairment. Reduced ROM (↓28%), increased movement time (↑47%) and finger coordination deficits. Compensatory wrist movement noted; distal fingers more affected than proximal.','Continue structured rehabilitation. Reassess in 4 weeks. Track inter-session ROM and coordination trends.','Established biomarker',
  'Simulated demonstration profile only. Post-stroke assessment requires multi-modal clinical evaluation.',
  [['ROM (affected)','59°','82°','moderate','Reduced flexion, greater in distal fingers'],['Finger Coordination','Reduced','Normal','moderate','Inter-finger coordination below reference'],['Wrist Compensation','Elevated','Minimal','moderate','Compensatory wrist movement during flexion'],['Movement Time','1.6s','1.1s','mild','Moderately prolonged'],['Grip Strength','60%','100%','moderate','Grip force below reference'],['EMG Activation','Reduced','Normal','mild','Lower amplitude, especially distal']]),
 stroke_severe:P('stroke_severe','Post-Stroke (Severe)','Neurological','#ef4444','High',[.38,.32,2.4,3.5,5.5,680,.3,.9,.25,.42,2.2,.8,.5],[.42,.35,.3,.22],'Simulated severe upper limb paresis following stroke',
  'Features of severe upper-limb motor impairment. Markedly reduced ROM (↓62%), highly fragmented trajectory and near-absent distal finger function. Significant compensatory wrist flexion throughout. Intensive neurorehabilitation indicated.','Urgent physiotherapy referral. High-intensity upper limb rehabilitation. Reassess in 2 weeks.','Established biomarker',
  'Simulated demonstration profile only. Severity requires standardized assessment (e.g., NIHSS, Fugl-Meyer).',
  [['ROM (affected)','31°','82°','significant','Severely reduced, distal worst (ring 27°, pinky 24°)'],['Movement Time','3.4s','1.1s','significant','Markedly prolonged'],['Initiation Delay','680ms','<100ms','significant','Severely delayed initiation'],['Trajectory Fragmentation','High','None','significant','Velocity plateaus indicate fragmented control'],['Grip Strength','25%','100%','significant','Severely reduced grip force'],['EMG','Sparse','Normal','significant','Very low amplitude, irregular bursts']]),
 hand_oa:P('hand_oa','Hand Osteoarthritis','Musculoskeletal','#eab308','Mod',[.68,.73,1.3,.8,10,180,.72,.2,.55,.8,1.2,.35,0],[.7,.68,.72,.74],'Simulated features associated with hand osteoarthritis',
  'Reduced hand function: ROM reduction (↓32%) without tremor, reduced speed and altered grip pattern. Stiffness-related characteristics (hesitation, reduced smoothness) consistent with musculoskeletal limitation.','Occupational therapy referral. Hand function assessment. Grip strengthening program.','Emerging evidence',
  'Simulated demonstration profile. Musculoskeletal assessment requires clinical examination and imaging.',
  [['ROM','56°','82°','moderate','Reduced flexion without neurological cause'],['Tremor','Minimal','Minimal','normal','No pathological tremor — distinguishes from neurological patterns'],['Movement Speed','1.5s','1.1s','mild','Slowed, consistent with pain-related guarding'],['Initiation Pattern','Hesitant','Smooth','mild','Brief hesitation consistent with pain avoidance'],['Grip Strength','55%','100%','moderate','Reduced grip force'],['Wrist Compensation','Moderate','Minimal','mild','Wrist compensates to reduce joint stress']]),
 tremor_essential:P('tremor_essential','Essential Tremor','Neurological','#06b6d4','Mod',[.88,.78,2.2,9,9.5,100,.45,.25,.82,.92,2.5,.2,1.2],[.9,.88,.88,.85],'Simulated kinetic/postural essential tremor characteristics',
  'High-frequency kinetic oscillation (~9–10Hz) over otherwise preserved voluntary movement. ROM and initiation near-normal, distinguishing it from the Parkinsonian pattern. Amplitude markedly elevated (9°), most prominent during active movement.','Neurology referral for tremor evaluation. Distinguish from other tremor disorders.','Emerging evidence',
  'Simulated profile. Essential tremor diagnosis requires clinical examination and tremor analysis.',
  [['Tremor Frequency','9.5Hz','<2Hz','significant','ET range 8–12Hz vs PD 4–6Hz'],['Tremor Amplitude','9°','<1°','significant','Markedly elevated kinetic tremor'],['Resting Tremor','Minimal','Minimal','normal','Kinetic/postural, not resting — key distinction from PD'],['ROM','72°','82°','mild','Voluntary range relatively preserved'],['Initiation Delay','100ms','<100ms','normal','Near-normal, unlike Parkinson\'s'],['EMG Burst Pattern','Rhythmic','Smooth','moderate','Alternating agonist-antagonist bursts at tremor frequency']]),
 mnd_early:P('mnd_early','MND / ALS (Early)','Neuromuscular','#ec4899','High',[.75,.6,1.6,3,7,280,.58,.45,.45,.55,2,.4,.4],[.75,.72,.7,.65],'Simulated early upper and lower motor neuron involvement features',
  'Features consistent with a progressive upper motor neuron pattern: reduced speed, elevated variability and altered EMG. Grip strength reduced out of proportion to ROM. Differs from Parkinsonian and musculoskeletal profiles.','Urgent neurology referral. Multidisciplinary assessment. Quantitative motor baseline established.','Research only',
  'Simulated profile for research. MND/ALS diagnosis requires specialist neurological evaluation, EMG/nerve conduction studies and clinical criteria.',
  [['Grip Strength','45%','100%','significant','Weakness disproportionate to ROM'],['EMG Amplitude','55%','100%','significant','Reduced motor unit recruitment'],['Fatigue Index','High','Low','significant','Rapid force decline across repetitions'],['Movement Speed','1.8s','1.1s','moderate','Upper motor neuron slowing'],['Finger Coordination','Reduced','Normal','moderate','Loss of independent finger control']]),
 cerebral_palsy:P('cerebral_palsy','Cerebral Palsy (Spastic)','Neuromuscular','#a855f7','High',[.5,.45,2,4,5,350,.38,.6,.4,1.3,2.5,.65,.6],[.52,.48,.5,.45],'Simulated spastic upper limb pattern with co-contraction',
  'Spastic upper-limb pattern: significantly reduced ROM, prolonged fragmented trajectory with co-contraction evidence (elevated baseline EMG) and high compensatory wrist movement.','Occupational therapy and physiotherapy. Spasticity management review. Track functional change longitudinally.','Research only',
  'Simulated spastic pattern for research and educational demonstration.',
  [['Resting EMG','Elevated','Minimal','significant','Baseline EMG consistent with spastic co-contraction'],['ROM','41°','82°','significant','Limited by spasticity and reduced voluntary control'],['Smoothness','Low','High','significant','Catch-and-release pattern'],['Wrist Compensation','High','Minimal','significant','Marked compensatory wrist flexion'],['Co-contraction','Detected','None','significant','Simultaneous agonist-antagonist activation']]),
 diabetic_neuropathy:P('diabetic_neuropathy','Diabetic Neuropathy','Neuromuscular','#84cc16','Mild',[.82,.8,1.6,1.5,10,200,.75,.3,.7,.75,1.5,.2,.1],[.85,.83,.8,.75],'Simulated reduced fine motor control consistent with peripheral neuropathy',
  'Distal-to-proximal gradient: distal finger ROM and coordination proportionally more reduced than proximal. Grip strength reduced with relatively preserved ROM, suggesting neuromuscular rather than musculoskeletal cause.','Endocrinology and neurology cross-referral. HbA1c monitoring. Nerve conduction studies.','Research only',
  'Simulated profile. Peripheral neuropathy diagnosis requires nerve conduction studies and clinical assessment.',
  [['Distal-Proximal Gradient','Detected','None','moderate','Length-dependent neuropathy pattern'],['Pinky ROM','62°','82°','moderate','Distal (ulnar) finger most affected'],['Index ROM','70°','82°','mild','Proximal (radial) finger relatively preserved'],['Grip Strength','70%','100%','mild','Reduced intrinsic muscle strength'],['Fine Motor Variability','Elevated','Low','mild','Reduced proprioceptive feedback']]),
 carpal_tunnel:P('carpal_tunnel','Carpal Tunnel Syndrome','Musculoskeletal','#0ea5e9','Mild',[.78,.82,1.4,1,10,150,.8,.4,.62,.68,1.3,.15,0],[.72,.75,.85,.88],'Simulated median nerve compression with radial digit involvement',
  'Radial digit distribution of impairment: index and middle fingers more affected than ring and pinky. Thenar EMG reduced; pinch grip more impaired than power grip. Consistent with median nerve distribution.','Orthopaedic or hand surgery referral. Nerve conduction studies. Ergonomic assessment.','Research only',
  'Simulated profile. CTS diagnosis requires nerve conduction studies and clinical examination.',
  [['Median Nerve Distribution','Detected','None','moderate','Index+middle more affected than ring+pinky'],['Index ROM','59°','82°','moderate','Most impaired (median innervation)'],['Pinky ROM','72°','82°','mild','Relatively preserved (ulnar territory)'],['Thenar EMG','68%','100%','moderate','Reduced thenar activation'],['Pinch vs Power Grip','Pinch ↓40%','Equal','moderate','Selective pinch impairment']])}
const smooth=(t:number)=>{t=Math.max(0,Math.min(1,t));return t*t*(3-2*t)}
// 10 s of simulated frames, pre-generated (not on the fly)
export function generateFrames(condition:ConditionKey,durationMs=10000,hz=50):SimFrame[]{
 const p=CONDITIONS[condition],frames:SimFrame[]=[],dt=1000/hz,rep=2200/p.speedScale,init=.05+p.initiationDelay/rep
 const repGain:number[]=Array.from({length:12},()=>1+(Math.random()-.5)*.15*p.variabilityScale)
 for(let t=0;t<durationMs;t+=dt){
  const ph=(t%rep)/rep,g=repGain[Math.floor(t/rep)]??1,rom=82*p.romScale*g
  const a=ph<init?0:ph<init+.35?rom*smooth((ph-init)/.35):ph<.7?rom:rom*(1-smooth((ph-.7)/.3))
  const tr=2*Math.PI*p.tremorFrequency*t/1000,tremor=p.tremorAmplitude*Math.sin(tr)*(.7+.3*Math.sin(tr*1.3)),noise=(Math.random()-.5)*p.variabilityScale*3
  const fingers=p.fingerModifiers.map((m,i)=>Math.max(0,Math.min(90,a*m+tremor*(i<2?1:.8)+noise*m)))
  const emg=Math.max(0,Math.min(100,(a/82)*100*p.emgScale+(Math.random()-.5)*20*p.emgVariabilityScale+Math.sin(tr*2)*5*p.emgScale))
  const prev=frames[frames.length-1],avgF=fingers.reduce((x,y)=>x+y,0)/4,velocity=prev?Math.abs(avgF-prev.fingers.reduce((x,y)=>x+y,0)/4)/(dt/1000):0
  frames.push({t,fingers,thumb:Math.max(0,Math.min(45,a*.35*p.fingerModifiers[0])),wristPitch:a*p.wristCompensation*.3+tremor*p.wristTremorScale,wristRoll:tremor*p.wristTremorScale*.4,emg,velocity,acceleration:0,jerk:0})}
 return frames}
